# Generated by Django 5.1.3 on 2025-01-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="user",
            new_name="name",
        ),
    ]
