# Generated by Django 5.1.3 on 2025-01-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_user_attendance_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
