# Generated by Django 5.1.3 on 2025-01-17 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_user_id_alter_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date",
            field=models.DateField(default=datetime.date(2025, 1, 17)),
        ),
    ]
