# Generated by Django 5.1.3 on 2025-01-17 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
