# Generated by Django 5.1.3 on 2025-01-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="status",
        ),
    ]
