# Generated by Django 5.1.3 on 2025-01-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_attendance_date_alter_attendance_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.CharField(default="0", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(upload_to=""),
        ),
    ]
