# Generated by Django 5.1.3 on 2025-01-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_user_id_alter_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(default="0", max_length=50),
        ),
    ]
