# Generated by Django 5.1.3 on 2025-01-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="user_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
